var y=Object.defineProperty;var E=(o,e,t)=>e in o?y(o,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):o[e]=t;var d=(o,e,t)=>(E(o,typeof e!="symbol"?e+"":e,t),t);import{a as L,S as b,i as u}from"./assets/vendor-da186403.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const m=class m{constructor(){this.query=null,this.totalResult=0,this.currentPage=1}async getImages(){const e="https://pixabay.com/api/",t={params:{key:"42200986-2d8f017897691a4245488f945",q:this.query,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:this.currentPage,per_page:m.PAGE_SIZE}};try{return(await L.get(e,t)).data}catch(n){throw console.error("Error fetching images:",n),n}}};d(m,"PAGE_SIZE",15);let c=m;const v=document.querySelector(".gallery-list");function S({webformatURL:o,largeImageURL:e,tags:t,likes:n,views:r,comments:s,downloads:l}){return` <a href="${e}" class="gallery">
    <figure class="gallery-figure"> 
     <img src="${o}" alt="${t}" class="gallery-img"/>
     <figcaption class="gallery-figcaption">
     <div class="img-item">Likes <span class="img-elem">${n}</span></div>
     <div class="img-item">View <span class="img-elem">${r}</span></div>
     <div class="img-item">Comments <span class="img-elem">${s}</span></div>
     <div class="img-item">Downloads <span class="img-elem">${l}</span></div>
     </figcaption>
     </figure>
     </a>`}function g(o){const e=o.map(S).join("");v.insertAdjacentHTML("beforeend",e),new b(".gallery-list a").refresh()}const i={formElem:document.querySelector(".form"),inputElem:document.querySelector(".form-input"),btnElem:document.querySelector(".form-button"),galleryElem:document.querySelector(".gallery-list"),btnLoadMoreElem:document.querySelector(".btn-load-more"),loaderElem:document.querySelector(".loader")},a=new c;i.formElem.addEventListener("submit",q);async function q(o){o.preventDefault(),p();const e=o.target.elements.query.value.trim();if(e){a.query=e,a.currentPage=1,i.galleryElem.innerHTML="";try{const t=await a.getImages();a.totalResult=t.totalHits,g(t.hits)}catch(t){a.totalResult=0,u.error({title:"Error",message:t.message})}h(),f(),i.formElem.reset()}}i.btnLoadMoreElem.addEventListener("click",P);async function P(){p(),a.currentPage+=1;const o=await a.getImages();g(o.hits),h(),f();const e=document.querySelector(".gallery-img").getBoundingClientRect().height;window.scrollBy({top:2*e,behavior:"smooth"})}function f(){Math.ceil(a.totalResult/c.PAGE_SIZE)<=a.currentPage?(i.btnLoadMoreElem.classList.add("hidden"),a.totalResult===0?u.show({message:`"We're sorry, there are no results."`,position:"topRight",color:"red"}):u.show({message:`"We're sorry, but you've reached the end of search results."`,position:"topRight",color:"blue"})):i.btnLoadMoreElem.classList.remove("hidden")}function p(){i.loaderElem.classList.remove("hidden"),i.btnLoadMoreElem.classList.add("hidden")}function h(){i.loaderElem.classList.add("hidden"),i.btnLoadMoreElem.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
