import{i as y,a as h}from"./assets/vendor-8cce9181.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const s={formElem:document.querySelector(".form"),inputElem:document.querySelector(".form-input"),btnElem:document.querySelector(".form-button"),galleryElem:document.querySelector(".gallery-list"),btnLoadMoreElem:document.querySelector(".btn-load-more"),loaderElem:document.querySelector(".loader")};let c=null,d=0,l=1;const L=15;async function m(){const r="https://pixabay.com/api/",t={params:{key:"42200986-2d8f017897691a4245488f945",q:c,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:l,per_page:15}};return(await h.get(r,t)).data}s.formElem.addEventListener("submit",E);async function E(r){r.preventDefault(),g();const t=r.target.elements.query.value.trim();if(!t)return;c=t,l=1,s.galleryElem.innerHTML="";const a=await m();d=a.totalHits,console.log(a),u(a.hits),p(),f(),s.formElem.reset()}function b({webformatURL:r,largeImageURL:t,tags:a,likes:i,views:e,comments:o,downloads:n}){return` <a href="${t}" class="gallery">
    <figure class="gallery-figure"> 
     <img src="${r}" alt="${a}" class="gallery-img"/>
     <figcaption class="gallery-figcaption">
     <div class="img-item">Likes <span class="img-elem">${i}</span></div>
     <div class="img-item">View <span class="img-elem">${e}</span></div>
     <div class="img-item">Comments <span class="img-elem">${o}</span></div>
     <div class="img-item">Downloads <span class="img-elem">${n}</span></div>
     </figcaption>
     </figure>
     </a>`}function u(r){const t=r.map(b).join("");s.galleryElem.insertAdjacentHTML("beforeend",t)}s.btnLoadMoreElem.addEventListener("click",v);async function v(){g(),l+=1;const r=await m();u(r.hits),p(),f();const t=document.querySelector(".gallery-img").getBoundingClientRect().height;window.scrollBy({top:2*t,behavior:"smooth"})}function f(){Math.ceil(d/L)<=l?(s.btnLoadMoreElem.classList.add("hidden"),y.show({message:`"We're sorry, but you've reached the end of search results."`,color:"blue"})):s.btnLoadMoreElem.classList.remove("hidden")}function g(){s.loaderElem.classList.remove("hidden"),s.btnLoadMoreElem.classList.add("hidden")}function p(){s.loaderElem.classList.add("hidden"),s.btnLoadMoreElem.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
