var y=Object.defineProperty;var E=(s,e,t)=>e in s?y(s,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):s[e]=t;var u=(s,e,t)=>(E(s,typeof e!="symbol"?e+"":e,t),t);import{a as L,S as b,i as c}from"./assets/vendor-da186403.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const d=class d{constructor(){this.query=null,this.totalResult=0,this.currentPage=1}async getImages(){const e="https://pixabay.com/api/",t={params:{key:"42200986-2d8f017897691a4245488f945",q:this.query,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:this.currentPage,per_page:d.PAGE_SIZE}};try{return(await L.get(e,t)).data}catch(l){throw console.error("Error fetching images:",l),l}}};u(d,"PAGE_SIZE",15);let m=d;const v=document.querySelector(".gallery-list");function S({webformatURL:s,largeImageURL:e,tags:t,likes:l,views:r,comments:o,downloads:n}){return` <a href="${e}" class="gallery">
    <figure class="gallery-figure"> 
     <img src="${s}" alt="${t}" class="gallery-img"/>
     <figcaption class="gallery-figcaption">
     <div class="img-item">Likes <span class="img-elem">${l}</span></div>
     <div class="img-item">View <span class="img-elem">${r}</span></div>
     <div class="img-item">Comments <span class="img-elem">${o}</span></div>
     <div class="img-item">Downloads <span class="img-elem">${n}</span></div>
     </figcaption>
     </figure>
     </a>`}function g(s){const e=s.map(S).join("");v.insertAdjacentHTML("beforeend",e),new b(".gallery-list a").refresh()}const i={formElem:document.querySelector(".form"),inputElem:document.querySelector(".form-input"),btnElem:document.querySelector(".form-button"),galleryElem:document.querySelector(".gallery-list"),btnLoadMoreElem:document.querySelector(".btn-load-more"),loaderElem:document.querySelector(".loader")},a=new m;i.formElem.addEventListener("submit",q);async function q(s){s.preventDefault(),h();const e=s.target.elements.query.value.trim();if(!e){i.loaderElem.classList.add("hidden"),c.show({message:"Please enter your search query.",position:"topRight",color:"red"});return}a.query=e,a.currentPage=1,i.galleryElem.innerHTML="";try{const t=await a.getImages();a.totalResult=t.totalHits,g(t.hits)}catch(t){a.totalResult=0,c.error({title:"Error",message:t.message})}p(),f(),i.formElem.reset()}i.btnLoadMoreElem.addEventListener("click",w);async function w(){h();try{a.currentPage+=1;const e=await a.getImages();g(e.hits)}catch(e){a.totalResult=0,c.error({title:"Error",message:e.message})}p(),f();const s=document.querySelector(".gallery-img").getBoundingClientRect().height;window.scrollBy({top:2*s,behavior:"smooth"})}function f(){Math.ceil(a.totalResult/m.PAGE_SIZE)<=a.currentPage?(i.btnLoadMoreElem.classList.add("hidden"),a.totalResult===0?c.show({message:"We're sorry, there are no results.",position:"topRight",color:"red"}):c.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):i.btnLoadMoreElem.classList.remove("hidden")}function h(){i.loaderElem.classList.remove("hidden"),i.btnLoadMoreElem.classList.add("hidden")}function p(){i.loaderElem.classList.add("hidden"),i.btnLoadMoreElem.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
